version: "3.7"

services:
  fastapi:
    image: "${FASTAPI_IMAGE_NAME:-fastapi}:${FASTAPI_IMAGE_TAG:-latest}"
    build:
      context: fastapi-01
      dockerfile: Dockerfile
      target: ${FASTAPI_BUILD_TARGET:-fastapi}
    ports:
      - "8000:8000"
    environment:
      FASTAPI_IMAGE_NAME: ${FASTAPI_IMAGE_NAME:-fastapi}
      FASTAPI_IMAGE_TAG: ${FASTAPI_IMAGE_TAG:-latest}
      FASTAPI_BUILD_TARGET: ${FASTAPI_BUILD_TARGET:-fastapi}
    volumes:
      - ./fastapi-01/src:/src
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
